### PR TITLE
entrypoint: handle jq error

### PR DESCRIPTION
**Pull request by pkeroulas**
Rename the tmp conf file only when jq has worked, otherwise the config file is empty.

### CODE REVIEW

**Review by rhastie — COMMENTED** [review]
@pkeroulas - Thanks for this...

I'm just trying to understand the execution flow in the scenario where jq fails...

jq fails I'm assuming as you've passed a ".conf" file using the volume switch with something jq doesn't like? It doesn't fail against the default ".conf" files.
jq fails so it doesn't create the ".tmp" file? Or does it create a blank one? I am assuming it doesn't create one...
The cp command fails as there is no ".tmp" file when jq fails and as such you are left with the default ".conf" file...

Is this what we want? In scenarios whereby jq fails do we want to revert to the default ".conf" file or should the container terminating due to an error in the entrypoint script highlight you to an ".conf" file problem?

I think this comes back to the original question - You've obviously seen this in practice. What scenario does jq fail? I think we need to decide on what we should do against this scenario - error/terminate or use the default ".conf" file. Can you add some further explanation on this please. Thanks

**Comment by pkeroulas** [comment]
I had pushed an old commit with 'cp' instead of 'mv'. The branch is now uptodate.
I had a situation with a syntax error in the conf leading with a temporary file created but empty.
More precisely, there was a comment in which would still be accepted by the app but not jq.
Do we want to flag that and exit?  That's a possibility.

**Review by rhastie — APPROVED** [review]
@pkeroulas Actually - that's very interesting commentary - I am aware that "jq" is very strict on json syntax and as such really dislikes comments... Possibly we should check for comments in the ".conf" files ahead of parsing them and either exit or strip them to the end of the line. This will need thinking about some more.

In the interim I see no issues with merging this to resolve your issue. Thanks for the pull request...

**Comment by pkeroulas** [comment]
> we should check for comments in the ".conf" files ahead of parsing them and either exit or strip them to the end of the line.

Right, I think the syntax should be validated (just a simple 'jq' read may be enough) but I would notify and exit rather than trying to handle any possible syntax error.

**Pull request closed without merging**
